dist: bionic
sudo: false

language: c++
compiler: gcc

addons:
  apt:
    packages:
    - libelf-dev
    - expect

cache:
  directories:
    - DEPENDS

jobs:
  include:
    - name: "SystemC 2.3.0a"
      env:  BUILD=RELEASE SYSTEMC=systemc-2.3.0a

    - name: "SystemC 2.3.1a"
      env:  BUILD=RELEASE SYSTEMC=systemc-2.3.1a

    - name: "SystemC 2.3.2"
      env:  BUILD=RELEASE SYSTEMC=systemc-2.3.2

    - name: "SystemC 2.3.3"
      env:  BUILD=RELEASE SYSTEMC=systemc-2.3.3

install:
  - mkdir -p DEPENDS && cd DEPENDS
  - export SYSTEMC_HOME=`pwd`/$SYSTEMC
  - export TARGET_ARCH=linux64
  - | # Build SystemC
      if [ ! -d $SYSTEMC_HOME ]; then
          wget http://www.accellera.org/images/downloads/standards/systemc/$SYSTEMC.tar.gz
          tar -xzf $SYSTEMC.tar.gz && cd $SYSTEMC
          mkdir BUILD && cd BUILD
          ../configure --enable-static CXXFLAGS="-std=c++11"
          make -j 4 && make install
          cd ../..
          rm -rf $SYSTEMC.tar.gz $SYSTEMC/BUILD
      fi
  - export VCML_HOME=`pwd`/vcml
  - | # Build vcml
      if [ ! -d vcml ]; then
          git clone https://github.com/janweinstock/vcml.git
      fi
      cd vcml && git pull origin master && cd ..
  - export OR1KISS_HOME=`pwd`/or1kiss
  - | # Build or1kiss
      if [ ! -d or1kiss ]; then
          git clone https://github.com/janweinstock/or1kiss.git
      fi
      cd or1kiss && git pull origin master && cd ..
  - cd ..

before_script:
  - mkdir $BUILD && cd $BUILD
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD

script:
  - make -j 4 && ctest --output-on-failure
