dist: trusty
sudo: false

language: c++

compiler:
  - gcc

addons:
  apt:
    packages:
    - libelf-dev

cache:
  directories:
    - DEPENDS

env:
  - BUILD=RELEASE TARGET_ARCH=linux64 SYSTEMC=systemc-2.3.0a
  - BUILD=RELEASE TARGET_ARCH=linux64 SYSTEMC=systemc-2.3.1a
  - BUILD=RELEASE TARGET_ARCH=linux64 SYSTEMC=systemc-2.3.2

install:
  - mkdir -p DEPENDS && cd DEPENDS
  - export SYSTEMC_HOME=`pwd`/$SYSTEMC
  - export TARGET_ARCH=linux64
  - | # Build SystemC
      if [ ! -d $SYSTEMC_HOME ]; then
          wget http://www.accellera.org/images/downloads/standards/systemc/$SYSTEMC.tar.gz
          tar -xzf $SYSTEMC.tar.gz && cd $SYSTEMC
          mkdir BUILD && cd BUILD
          ../configure --enable-static CXXFLAGS="-std=c++11"
          make -j 4 && make install
          cd ../..
          rm -rf $SYSTEMC.tar.gz $SYSTEMC/BUILD
      fi
  - export VCML_HOME=`pwd`/vcml/$BUILD
  - | # Build vcml
      if [ ! -d vcml ]; then
          git clone https://github.com/janweinstock/vcml.git
      fi
      cd vcml && git pull origin master
      mkdir -p $BUILD/BUILD && cd $BUILD/BUILD
      cmake ../.. -DCMAKE_INSTALL_PREFIX=$VCML_HOME -DCMAKE_BUILD_TYPE=$BUILD
      make -j 4 && make install
      cd ../../..
      rm -rf vcml/$BUILD/BUILD
  - export OR1KISS_HOME=`pwd`/or1kiss/$BUILD
  - | # Build or1kiss
      if [ ! -d or1kiss ]; then
          git clone https://github.com/janweinstock/or1kiss.git
      fi
      cd or1kiss && git pull origin master
      mkdir -p $BUILD/BUILD && cd $BUILD/BUILD
      cmake ../.. -DCMAKE_INSTALL_PREFIX=$OR1KISS_HOME -DCMAKE_BUILD_TYPE=$BUILD -DBUILD_SW=OFF
      make -j 4 && make install
      cd ../../..
      rm -rf or1kiss/$BUILD/BUILD
  - cd ..

before_script:
  - mkdir $BUILD && cd $BUILD
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD

script:
  - make
