#!/bin/bash -e

 ##############################################################################
 #                                                                            #
 # Copyright 2018 Jan Henrik Weinstock                                        #
 #                                                                            #
 # Licensed under the Apache License, Version 2.0 (the "License");            #
 # you may not use this file except in compliance with the License.           #
 # You may obtain a copy of the License at                                    #
 #                                                                            #
 #     http://www.apache.org/licenses/LICENSE-2.0                             #
 #                                                                            #
 # Unless required by applicable law or agreed to in writing, software        #
 # distributed under the License is distributed on an "AS IS" BASIS,          #
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
 # See the License for the specific language governing permissions and        #
 # limitations under the License.                                             #
 #                                                                            #
 ##############################################################################

ethdev="eth1"
tapdev="tap0"
ipaddr="10.0.0.1"

if ! [ -x "$(command -v tunctl)" ]; then
    echo 'Error: tunctl (uml-utilities) is not installed.' >&2
    exit 1
fi

if [ -z $SUDO_USER ]; then
    echo "Error: please run with sudo, e.g. 'sudo $0 $@'" >&2
    exit 1
fi

start() {
    # check if TAP device is already running
    if [ -n "`grep $tapdev /proc/net/dev`" ]; then
        echo "TAP device $tapdev already running"
        exit 1
    fi

    # get input from user, we need to know which ethernet device is used
    read -p "Specify host network interface: " -ei $ethdev ethdev
    read -p "Specify local NAT IP for host:  " -ei $ipaddr ipaddr

    # create a TAP device for the current user (needs root priv.)
    echo "Starting $tapdev with IP address $ipaddr for user $SUDO_USER"
    tunctl -t $tapdev -u $SUDO_USER

    # assign local (NAT) IP address
    ifconfig $tapdev $ipaddr promisc up

    # enable NAT
    echo "Starting NAT"
    modprobe iptable_nat
    echo 1 > /proc/sys/net/ipv4/ip_forward
    iptables -t nat -A POSTROUTING -o $ethdev -j MASQUERADE
    iptables -F FORWARD
    iptables -A FORWARD -i $tapdev -j ACCEPT
}

stop() {
    if [ -z "`grep $tapdev /proc/net/dev`" ] ; then
        echo "TAP device $tapdev not active"
        exit 1
    fi

    # disable NAT
    echo "Stopping NAT"
    echo 0 > /proc/sys/net/ipv4/ip_forward
    iptables -F FORWARD
    iptables -A FORWARD -j REJECT --reject-with icmp-host-prohibited
    iptables -t nat -F

    # stop and remove TAP device
    echo "Stopping $tapdev"
    ifconfig $tapdev down
    tunctl -d $tapdev
}

restart() {
    stop
    start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 2
esac

exit $?
